# Sphinx configuration for the GATE-01 typst `lang` gate's German
# LINKAGE proof (Phase 27.1, CONF-07, SC#1's D-07 "supplement linkage
# half").
#
# This is the fixture that proves the text-language setting actually
# DRIVES Typst's generated figure/table supplement labels -- the motivating
# outcome for this whole phase (Phase 25's captioned table getting "Tabelle
# 1" instead of "Table 1" once `language = "de"` is set). `de` was chosen
# over `ja` for this half of the proof because "Abbildung"/"Tabelle" are
# Latin-script and stable across every OS/font configuration, whereas CJK
# glyph extraction depends on system font availability the CI ubuntu
# runner has never confirmed (27.1-CONTEXT.md D-07).
#
# Before this phase's fix, `templates/base.typ` hardcoded
# `set text(size: fontsize, lang: "en")` -- so this build would have
# produced "Figure 1"/"Table 1" regardless of this `language` setting
# (the durable pre-fix-basis reconstruction in
# ``TestPreFixBasisFailureProof`` recreates exactly this shape).
#
# Content is ASCII-only -- the German words this case asserts on are
# GENERATED by Typst from the `lang` setting, never written in this
# fixture's own prose.
#
# Uses the DEFAULT (unset `typst_template`/`typst_package`) template
# path -- `lang` is only auto-derived on that path (D-06/CONF-07).

project = "Typst Lang Gate German Linkage Proof"
author = "Test Author"
release = "1.0.0"

extensions = ["typsphinx"]

# index must be a master document (not merely an included one) so the
# writer applies the full template routing and TypstPDFBuilder.finish()
# actually compiles it to PDF.
typst_documents = [
    ("index", "index", project, author),
]

# The Sphinx language whose Typst-lang conversion this fixture proves
# drives the compiled PDF's figure/table supplement text (D-02: "de" ->
# "de" -- "Abbildung"/"Tabelle").
language = "de"
